source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JSSAlertView_Example' do
  pod 'JSSAlertView', :path => '../'
end

target 'JSSAlertView_Tests' do
  pod 'JSSAlertView', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase', '~> 2.1.2'
  pod 'Nimble-Snapshots'
end
